name: Node.js CI

on:
Â  push:
Â  Â  branches:
Â  Â  Â  - main
Â  pull_request:
Â  Â  branches:
Â  Â  Â  - main
Â  schedule:
Â  Â  - cron: '0 */6 * * *'  # BY ğ™-ğ™ğ¢ğœÂ 

jobs:
Â  build:

Â  Â  runs-on: ubuntu-latest

Â  Â  strategy:
Â  Â  Â  matrix:
Â  Â  Â  Â  node-version: [20.x]

Â  Â  steps:
Â  Â  - name: Checkout repository
Â  Â  Â  uses: actions/checkout@v3

Â  Â  - name: Set up Node.js
Â  Â  Â  uses: actions/setup-node@v3
Â  Â  Â  with:
Â  Â  Â  Â  node-version: ${{ matrix.node-version }}

Â  Â  - name: Install dependencies
Â  Â  Â  run: npm install

Â  Â  - name: Install FFmpeg
Â  Â  Â  run: sudo apt-get install -y ffmpeg

Â  Â  - name: Start application with timeout
Â  Â  Â  run: |
Â  Â  Â  Â  timeout 21590s npm start  # Limite l'exÃ©cution Ã  5h 59m 50s

Â  Â  - name: Save state (Optional)
Â  Â  Â  run: |
Â  Â  Â  Â  ./save_state.sh







































